package com.ivor.kriptex.deliverypolicy.adversarial

import com.ivor.kriptex.deliverypolicy.DeliveryMode
import org.junit.Test

class AdversarialConversationScenarioTest {

    private val runner = ConversationScenarioRunner()

    private fun pkt(id: String, from: ConversationScenario.Actor, to: ConversationScenario.Actor): ConversationScenario.PacketHandle {
        return ConversationScenario.PacketHandle(id = id, from = from, to = to, messageId = id)
    }

    @Test
    fun ack_before_outbound_is_enqueued_is_staged_and_does_not_break_invariants() {
        val c = "c_ack_before"
        val s = conversationScenario("ack_before_outbound") {
            ack(
                from = ConversationScenario.Actor.B,
                to = ConversationScenario.Actor.A,
                conversationId = c,
                ackMessageId = "ack1",
                ackedMessageId = "m_future",
            )
            receiveInbound(packet = pkt("ack1", from = ConversationScenario.Actor.B, to = ConversationScenario.Actor.A))

            sendOutbound(
                from = ConversationScenario.Actor.A,
                conversationId = c,
                peerId = "B",
                protocol = ConversationScenario.OutboundProtocol.User(
                    messageId = "m_future",
                    createdAtElapsedMs = 10L,
                    payload = byteArrayOf(1, 2, 3),
                ),
            )
        }

        runner.runScenario(s)
    }

    @Test
    fun duplicate_inbound_and_duplicate_ack_with_mid_restore_remains_invariant_safe() {
        val c = "c_dup_restore"
        val s = conversationScenario("dup_and_restore") {
            sendOutbound(
                from = ConversationScenario.Actor.A,
                conversationId = c,
                peerId = "B",
                protocol = ConversationScenario.OutboundProtocol.User(
                    messageId = "m1",
                    createdAtElapsedMs = 1L,
                    payload = byteArrayOf(9),
                ),
            )
            duplicate(packet = pkt("m1", from = ConversationScenario.Actor.A, to = ConversationScenario.Actor.B), times = 2)

            snapshotAndRestore(
                actors = setOf(ConversationScenario.Actor.A),
                targets = setOf(
                    ConversationScenario.RestoreTarget.MESSAGE_STORE,
                    ConversationScenario.RestoreTarget.LEDGER,
                    ConversationScenario.RestoreTarget.OUTBOX,
                    ConversationScenario.RestoreTarget.SESSION_PROTOCOL_ENGINE,
                ),
            )

            // Deliver first copy -> generates B->A ack1
            receiveInbound(packet = pkt("m1", from = ConversationScenario.Actor.A, to = ConversationScenario.Actor.B))

            // Duplicate and deliver ack twice.
            duplicate(packet = pkt("ack1", from = ConversationScenario.Actor.B, to = ConversationScenario.Actor.A), times = 2)
            receiveInbound(packet = pkt("ack1", from = ConversationScenario.Actor.B, to = ConversationScenario.Actor.A))
            receiveInbound(packet = pkt("ack1", from = ConversationScenario.Actor.B, to = ConversationScenario.Actor.A))

            // Deliver duplicate message copy; inbound pipeline must dedupe.
            receiveInbound(packet = pkt("m1", from = ConversationScenario.Actor.A, to = ConversationScenario.Actor.B))
        }

        runner.runScenario(s)
    }

    @Test
    fun reordered_delivery_and_reordered_acks_remain_invariant_safe() {
        val c = "c_reorder"
        val s = conversationScenario("reorder") {
            sendOutbound(from = ConversationScenario.Actor.A, conversationId = c, peerId = "B", protocol = ConversationScenario.OutboundProtocol.User("m1", 1L, byteArrayOf(1)))
            sendOutbound(from = ConversationScenario.Actor.A, conversationId = c, peerId = "B", protocol = ConversationScenario.OutboundProtocol.User("m2", 2L, byteArrayOf(2)))
            sendOutbound(from = ConversationScenario.Actor.A, conversationId = c, peerId = "B", protocol = ConversationScenario.OutboundProtocol.User("m3", 3L, byteArrayOf(3)))

            // Deliver in reverse: m3, m2, m1.
            reorder {
                receiveInbound(packet = pkt("m1", from = ConversationScenario.Actor.A, to = ConversationScenario.Actor.B))
                receiveInbound(packet = pkt("m2", from = ConversationScenario.Actor.A, to = ConversationScenario.Actor.B))
                receiveInbound(packet = pkt("m3", from = ConversationScenario.Actor.A, to = ConversationScenario.Actor.B))
            }

            // Acks generated by B will be ack1/ack2/ack3; deliver out-of-order too.
            reorder {
                receiveInbound(packet = pkt("ack1", from = ConversationScenario.Actor.B, to = ConversationScenario.Actor.A))
                receiveInbound(packet = pkt("ack2", from = ConversationScenario.Actor.B, to = ConversationScenario.Actor.A))
                receiveInbound(packet = pkt("ack3", from = ConversationScenario.Actor.B, to = ConversationScenario.Actor.A))
            }
        }

        runner.runScenario(s)
    }

    @Test
    fun passive_then_restore_outbox_then_upgrade_to_active_sends_without_duplication() {
        val c = "c_mode_restore"
        val s = conversationScenario("mode_flap_with_restore") {
            setDeliveryMode(actor = ConversationScenario.Actor.A, mode = DeliveryMode.PASSIVE)

            sendOutbound(
                from = ConversationScenario.Actor.A,
                conversationId = c,
                peerId = "B",
                protocol = ConversationScenario.OutboundProtocol.User(
                    messageId = "m1",
                    createdAtElapsedMs = 1L,
                    payload = byteArrayOf(7),
                ),
            )

            snapshotAndRestore(
                actors = setOf(ConversationScenario.Actor.A),
                targets = setOf(ConversationScenario.RestoreTarget.OUTBOX),
            )

            setDeliveryMode(actor = ConversationScenario.Actor.A, mode = DeliveryMode.ACTIVE)

            receiveInbound(packet = pkt("m1", from = ConversationScenario.Actor.A, to = ConversationScenario.Actor.B))
            receiveInbound(packet = pkt("ack1", from = ConversationScenario.Actor.B, to = ConversationScenario.Actor.A))
        }

        runner.runScenario(s)
    }

    @Test
    fun group_message_before_sender_key_distribution_is_rejected_then_distribution_unblocks_future_messages() {
        val c = "c_group"
        val s = conversationScenario("group_sender_key_order") {
            // B sends group message first (A should reject due to missing_sender_key).
            sendOutbound(
                from = ConversationScenario.Actor.B,
                conversationId = c,
                peerId = "A",
                protocol = ConversationScenario.OutboundProtocol.SenderKeyGroupMessage(
                    messageId = "gm1",
                    createdAtElapsedMs = 1L,
                    ciphertextPayload = byteArrayOf(42),
                ),
            )
            receiveInbound(packet = pkt("gm1", from = ConversationScenario.Actor.B, to = ConversationScenario.Actor.A))

            // Now B distributes sender key to A.
            sendOutbound(
                from = ConversationScenario.Actor.B,
                conversationId = c,
                peerId = "A",
                protocol = ConversationScenario.OutboundProtocol.SenderKeyDistributionPlanned(
                    messageId = "skd1",
                    createdAtElapsedMs = 2L,
                ),
            )
            receiveInbound(packet = pkt("skd1", from = ConversationScenario.Actor.B, to = ConversationScenario.Actor.A))
            // ACK of distribution from A -> B is ack1.
            receiveInbound(packet = pkt("ack1", from = ConversationScenario.Actor.A, to = ConversationScenario.Actor.B))

            // A still has no plaintext user message for gm1 (it was rejected), but next group message should decrypt.
            sendOutbound(
                from = ConversationScenario.Actor.B,
                conversationId = c,
                peerId = "A",
                protocol = ConversationScenario.OutboundProtocol.SenderKeyGroupMessage(
                    messageId = "gm2",
                    createdAtElapsedMs = 3L,
                    ciphertextPayload = byteArrayOf(43),
                ),
            )
            receiveInbound(packet = pkt("gm2", from = ConversationScenario.Actor.B, to = ConversationScenario.Actor.A))
            // ACK of decrypted user message from A -> B is ack2.
            receiveInbound(packet = pkt("ack2", from = ConversationScenario.Actor.A, to = ConversationScenario.Actor.B))
        }

        runner.runScenario(s)
    }

    @Test
    fun regression_lock_runs_all_scenarios_sequentially_with_fresh_harness() {
        val scenarios = listOf(
            conversationScenario("lock_ack_before") {
                val c = "c_lock1"
                ack(from = ConversationScenario.Actor.B, to = ConversationScenario.Actor.A, conversationId = c, ackMessageId = "ack1", ackedMessageId = "m_future")
                receiveInbound(packet = pkt("ack1", from = ConversationScenario.Actor.B, to = ConversationScenario.Actor.A))
                sendOutbound(from = ConversationScenario.Actor.A, conversationId = c, peerId = "B", protocol = ConversationScenario.OutboundProtocol.User("m_future", 10L, byteArrayOf(1)))
            },
            conversationScenario("lock_reorder") {
                val c = "c_lock2"
                sendOutbound(from = ConversationScenario.Actor.A, conversationId = c, peerId = "B", protocol = ConversationScenario.OutboundProtocol.User("m1", 1L, byteArrayOf(1)))
                sendOutbound(from = ConversationScenario.Actor.A, conversationId = c, peerId = "B", protocol = ConversationScenario.OutboundProtocol.User("m2", 2L, byteArrayOf(2)))
                reorder {
                    receiveInbound(packet = pkt("m1", from = ConversationScenario.Actor.A, to = ConversationScenario.Actor.B))
                    receiveInbound(packet = pkt("m2", from = ConversationScenario.Actor.A, to = ConversationScenario.Actor.B))
                }
            },
            conversationScenario("lock_group") {
                val c = "c_lock_group"
                sendOutbound(from = ConversationScenario.Actor.B, conversationId = c, peerId = "A", protocol = ConversationScenario.OutboundProtocol.SenderKeyDistributionPlanned("skd1", 1L))
                receiveInbound(packet = pkt("skd1", from = ConversationScenario.Actor.B, to = ConversationScenario.Actor.A))
            },
        )

        scenarios.forEach { runner.runScenario(it) }
    }
}
